name: monlivreur
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  email_validator: ^2.1.17

  introduction_screen: ^3.1.4
  shared_preferences: ^2.0.16
  percent_indicator: ^4.0.1
  enhance_stepper: ^0.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  flutter_rating_bar: ^4.0.1

  latlong2: ^0.8.1
  location: ^4.4.0
  flutter_map: ^3.1.0

  dio: ^4.0.6
  basic_utils: ^5.4.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4

  flutter_native_splash: ^2.2.16
  image_picker: ^0.8.6

  provider: ^5.0.0
  #open_street_map_search_and_pick: ^0.0.15
  url_launcher: ^6.1.7
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0

  auto_size_text: ^3.0.0
  pin_code_fields: ^7.4.0
  phone_number_text_field: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icone.png"
  adaptive_icon_background: "#FFD64D"
  adaptive_icon_foreground: "assets/icone.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 300
